*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF025................................*
FORM GET_DATA_ZABSF_PP_V_SF025.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP033 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF025 .
ZABSF_PP_V_SF025-MANDT =
ZABSF_PP033-MANDT .
ZABSF_PP_V_SF025-AREAID =
ZABSF_PP033-AREAID .
ZABSF_PP_V_SF025-WERKS =
ZABSF_PP033-WERKS .
ZABSF_PP_V_SF025-ARBPL =
ZABSF_PP033-ARBPL .
ZABSF_PP_V_SF025-FLAG_FORM =
ZABSF_PP033-FLAG_FORM .
ZABSF_PP_V_SF025-IMPR_OUT =
ZABSF_PP033-IMPR_OUT .
ZABSF_PP_V_SF025-SFORM =
ZABSF_PP033-SFORM .
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF025.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF025 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF025.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF025-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP033 WHERE
  AREAID = ZABSF_PP_V_SF025-AREAID AND
  WERKS = ZABSF_PP_V_SF025-WERKS AND
  ARBPL = ZABSF_PP_V_SF025-ARBPL AND
  FLAG_FORM = ZABSF_PP_V_SF025-FLAG_FORM .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP033 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP033 WHERE
  AREAID = ZABSF_PP_V_SF025-AREAID AND
  WERKS = ZABSF_PP_V_SF025-WERKS AND
  ARBPL = ZABSF_PP_V_SF025-ARBPL AND
  FLAG_FORM = ZABSF_PP_V_SF025-FLAG_FORM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP033.
    ENDIF.
ZABSF_PP033-MANDT =
ZABSF_PP_V_SF025-MANDT .
ZABSF_PP033-AREAID =
ZABSF_PP_V_SF025-AREAID .
ZABSF_PP033-WERKS =
ZABSF_PP_V_SF025-WERKS .
ZABSF_PP033-ARBPL =
ZABSF_PP_V_SF025-ARBPL .
ZABSF_PP033-FLAG_FORM =
ZABSF_PP_V_SF025-FLAG_FORM .
ZABSF_PP033-IMPR_OUT =
ZABSF_PP_V_SF025-IMPR_OUT .
ZABSF_PP033-SFORM =
ZABSF_PP_V_SF025-SFORM .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP033 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP033 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF025-UPD_FLAG,
STATUS_ZABSF_PP_V_SF025-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF025.
  SELECT SINGLE * FROM ZABSF_PP033 WHERE
AREAID = ZABSF_PP_V_SF025-AREAID AND
WERKS = ZABSF_PP_V_SF025-WERKS AND
ARBPL = ZABSF_PP_V_SF025-ARBPL AND
FLAG_FORM = ZABSF_PP_V_SF025-FLAG_FORM .
ZABSF_PP_V_SF025-MANDT =
ZABSF_PP033-MANDT .
ZABSF_PP_V_SF025-AREAID =
ZABSF_PP033-AREAID .
ZABSF_PP_V_SF025-WERKS =
ZABSF_PP033-WERKS .
ZABSF_PP_V_SF025-ARBPL =
ZABSF_PP033-ARBPL .
ZABSF_PP_V_SF025-FLAG_FORM =
ZABSF_PP033-FLAG_FORM .
ZABSF_PP_V_SF025-IMPR_OUT =
ZABSF_PP033-IMPR_OUT .
ZABSF_PP_V_SF025-SFORM =
ZABSF_PP033-SFORM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF025 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF025-AREAID TO
ZABSF_PP033-AREAID .
MOVE ZABSF_PP_V_SF025-WERKS TO
ZABSF_PP033-WERKS .
MOVE ZABSF_PP_V_SF025-ARBPL TO
ZABSF_PP033-ARBPL .
MOVE ZABSF_PP_V_SF025-FLAG_FORM TO
ZABSF_PP033-FLAG_FORM .
MOVE ZABSF_PP_V_SF025-MANDT TO
ZABSF_PP033-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP033'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP033 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP033'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
