*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF008................................*
FORM GET_DATA_ZABSF_PP_V_SF008.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP008 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF008 .
ZABSF_PP_V_SF008-MANDT =
ZABSF_PP008-MANDT .
ZABSF_PP_V_SF008-AREAID =
ZABSF_PP008-AREAID .
ZABSF_PP_V_SF008-WERKS =
ZABSF_PP008-WERKS .
ZABSF_PP_V_SF008-ENDDA =
ZABSF_PP008-ENDDA .
ZABSF_PP_V_SF008-BEGDA =
ZABSF_PP008-BEGDA .
ZABSF_PP_V_SF008-TAREA_ID =
ZABSF_PP008-TAREA_ID .
    SELECT SINGLE * FROM ZABSF_PP008_T WHERE
AREAID = ZABSF_PP008-AREAID AND
WERKS = ZABSF_PP008-WERKS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF008-AREA_DESC =
ZABSF_PP008_T-AREA_DESC .
    ENDIF.
    SELECT SINGLE * FROM ZABSF_PP059 WHERE
TAREA_ID = ZABSF_PP008-TAREA_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZABSF_PP059_T WHERE
TAREA_ID = ZABSF_PP059-TAREA_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF008-TAREA_DESC =
ZABSF_PP059_T-TAREA_DESC .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF008.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF008 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF008.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF008-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP008 WHERE
  AREAID = ZABSF_PP_V_SF008-AREAID AND
  WERKS = ZABSF_PP_V_SF008-WERKS AND
  ENDDA = ZABSF_PP_V_SF008-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP008 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP008_T WHERE
    AREAID = ZABSF_PP008-AREAID AND
    WERKS = ZABSF_PP008-WERKS AND
    SPRAS = SY-LANGU .
    IF SY-SUBRC = 0.
    SELECT COUNT(*) FROM ZABSF_PP008 WHERE
    AREAID EQ ZABSF_PP008_T-AREAID AND
    WERKS EQ ZABSF_PP008_T-WERKS .
      IF SY-DBCNT EQ 0.
    DELETE FROM ZABSF_PP008_T WHERE
    AREAID = ZABSF_PP008-AREAID AND
    WERKS = ZABSF_PP008-WERKS .
      ENDIF.
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP008 WHERE
  AREAID = ZABSF_PP_V_SF008-AREAID AND
  WERKS = ZABSF_PP_V_SF008-WERKS AND
  ENDDA = ZABSF_PP_V_SF008-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP008.
    ENDIF.
ZABSF_PP008-MANDT =
ZABSF_PP_V_SF008-MANDT .
ZABSF_PP008-AREAID =
ZABSF_PP_V_SF008-AREAID .
ZABSF_PP008-WERKS =
ZABSF_PP_V_SF008-WERKS .
ZABSF_PP008-ENDDA =
ZABSF_PP_V_SF008-ENDDA .
ZABSF_PP008-BEGDA =
ZABSF_PP_V_SF008-BEGDA .
ZABSF_PP008-TAREA_ID =
ZABSF_PP_V_SF008-TAREA_ID .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP008 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP008 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP008_T WHERE
    AREAID = ZABSF_PP008-AREAID AND
    WERKS = ZABSF_PP008-WERKS AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP008_T.
ZABSF_PP008_T-AREAID =
ZABSF_PP008-AREAID .
ZABSF_PP008_T-WERKS =
ZABSF_PP008-WERKS .
ZABSF_PP008_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP008_T-AREA_DESC =
ZABSF_PP_V_SF008-AREA_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP008_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP008_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF008-UPD_FLAG,
STATUS_ZABSF_PP_V_SF008-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF008.
  SELECT SINGLE * FROM ZABSF_PP008 WHERE
AREAID = ZABSF_PP_V_SF008-AREAID AND
WERKS = ZABSF_PP_V_SF008-WERKS AND
ENDDA = ZABSF_PP_V_SF008-ENDDA .
ZABSF_PP_V_SF008-MANDT =
ZABSF_PP008-MANDT .
ZABSF_PP_V_SF008-AREAID =
ZABSF_PP008-AREAID .
ZABSF_PP_V_SF008-WERKS =
ZABSF_PP008-WERKS .
ZABSF_PP_V_SF008-ENDDA =
ZABSF_PP008-ENDDA .
ZABSF_PP_V_SF008-BEGDA =
ZABSF_PP008-BEGDA .
ZABSF_PP_V_SF008-TAREA_ID =
ZABSF_PP008-TAREA_ID .
    SELECT SINGLE * FROM ZABSF_PP008_T WHERE
AREAID = ZABSF_PP008-AREAID AND
WERKS = ZABSF_PP008-WERKS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF008-AREA_DESC =
ZABSF_PP008_T-AREA_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF008-AREA_DESC .
    ENDIF.
    SELECT SINGLE * FROM ZABSF_PP059 WHERE
TAREA_ID = ZABSF_PP008-TAREA_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZABSF_PP059_T WHERE
TAREA_ID = ZABSF_PP059-TAREA_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF008-TAREA_DESC =
ZABSF_PP059_T-TAREA_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSF_PP_V_SF008-TAREA_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF008-TAREA_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF008 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF008-AREAID TO
ZABSF_PP008-AREAID .
MOVE ZABSF_PP_V_SF008-WERKS TO
ZABSF_PP008-WERKS .
MOVE ZABSF_PP_V_SF008-ENDDA TO
ZABSF_PP008-ENDDA .
MOVE ZABSF_PP_V_SF008-MANDT TO
ZABSF_PP008-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP008'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP008 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP008'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP008-AREAID TO
ZABSF_PP008_T-AREAID .
MOVE ZABSF_PP008-WERKS TO
ZABSF_PP008_T-WERKS .
MOVE SY-LANGU TO
ZABSF_PP008_T-SPRAS .
MOVE ZABSF_PP_V_SF008-MANDT TO
ZABSF_PP008_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP008_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP008_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP008_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZABSF_PP_V_SF008 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZABSF_PP008-MANDT =
ZABSF_PP_V_SF008-MANDT .
ZABSF_PP008-AREAID =
ZABSF_PP_V_SF008-AREAID .
ZABSF_PP008-WERKS =
ZABSF_PP_V_SF008-WERKS .
ZABSF_PP008-ENDDA =
ZABSF_PP_V_SF008-ENDDA .
ZABSF_PP008-BEGDA =
ZABSF_PP_V_SF008-BEGDA .
ZABSF_PP008-TAREA_ID =
ZABSF_PP_V_SF008-TAREA_ID .
  ZABSF_PP008_T-AREAID =
    ZABSF_PP008-AREAID .
  ZABSF_PP008_T-WERKS =
    ZABSF_PP008-WERKS .
  ZABSF_PP008_T-SPRAS =
    SY-LANGU .
ZABSF_PP008_T-AREA_DESC =
ZABSF_PP_V_SF008-AREA_DESC .
    SELECT SINGLE * FROM ZABSF_PP059 WHERE
TAREA_ID = ZABSF_PP008-TAREA_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZABSF_PP059_T WHERE
TAREA_ID = ZABSF_PP059-TAREA_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF008-TAREA_DESC =
ZABSF_PP059_T-TAREA_DESC .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSF_PP_V_SF008-TAREA_DESC .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF008-TAREA_DESC .
    ENDIF.
ENDFORM.
