*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF001................................*
FORM GET_DATA_ZABSF_PP_V_SF001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP001 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF001 .
ZABSF_PP_V_SF001-MANDT =
ZABSF_PP001-MANDT .
ZABSF_PP_V_SF001-AREAID =
ZABSF_PP001-AREAID .
ZABSF_PP_V_SF001-WERKS =
ZABSF_PP001-WERKS .
ZABSF_PP_V_SF001-SHIFTID =
ZABSF_PP001-SHIFTID .
ZABSF_PP_V_SF001-ENDDA =
ZABSF_PP001-ENDDA .
ZABSF_PP_V_SF001-BEGDA =
ZABSF_PP001-BEGDA .
ZABSF_PP_V_SF001-SHIFT_START =
ZABSF_PP001-SHIFT_START .
ZABSF_PP_V_SF001-SHIFT_END =
ZABSF_PP001-SHIFT_END .
ZABSF_PP_V_SF001-FCALID =
ZABSF_PP001-FCALID .
ZABSF_PP_V_SF001-PAUTY =
ZABSF_PP001-PAUTY .
ZABSF_PP_V_SF001-SHIFT_DOWN =
ZABSF_PP001-SHIFT_DOWN .
ZABSF_PP_V_SF001-SHIFT_UP =
ZABSF_PP001-SHIFT_UP .
ZABSF_PP_V_SF001-HOURS_CHG =
ZABSF_PP001-HOURS_CHG .
    SELECT SINGLE * FROM ZABSF_PP001_T WHERE
AREAID = ZABSF_PP001-AREAID AND
WERKS = ZABSF_PP001-WERKS AND
SHIFTID = ZABSF_PP001-SHIFTID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF001-SHIFT_DESC =
ZABSF_PP001_T-SHIFT_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP001 WHERE
  AREAID = ZABSF_PP_V_SF001-AREAID AND
  WERKS = ZABSF_PP_V_SF001-WERKS AND
  SHIFTID = ZABSF_PP_V_SF001-SHIFTID AND
  ENDDA = ZABSF_PP_V_SF001-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP001 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP001_T WHERE
    AREAID = ZABSF_PP001-AREAID AND
    WERKS = ZABSF_PP001-WERKS AND
    SHIFTID = ZABSF_PP001-SHIFTID AND
    SPRAS = SY-LANGU .
    IF SY-SUBRC = 0.
    SELECT COUNT(*) FROM ZABSF_PP001 WHERE
    AREAID EQ ZABSF_PP001_T-AREAID AND
    WERKS EQ ZABSF_PP001_T-WERKS AND
    SHIFTID EQ ZABSF_PP001_T-SHIFTID .
      IF SY-DBCNT EQ 0.
    DELETE FROM ZABSF_PP001_T WHERE
    AREAID = ZABSF_PP001-AREAID AND
    WERKS = ZABSF_PP001-WERKS AND
    SHIFTID = ZABSF_PP001-SHIFTID .
      ENDIF.
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP001 WHERE
  AREAID = ZABSF_PP_V_SF001-AREAID AND
  WERKS = ZABSF_PP_V_SF001-WERKS AND
  SHIFTID = ZABSF_PP_V_SF001-SHIFTID AND
  ENDDA = ZABSF_PP_V_SF001-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP001.
    ENDIF.
ZABSF_PP001-MANDT =
ZABSF_PP_V_SF001-MANDT .
ZABSF_PP001-AREAID =
ZABSF_PP_V_SF001-AREAID .
ZABSF_PP001-WERKS =
ZABSF_PP_V_SF001-WERKS .
ZABSF_PP001-SHIFTID =
ZABSF_PP_V_SF001-SHIFTID .
ZABSF_PP001-ENDDA =
ZABSF_PP_V_SF001-ENDDA .
ZABSF_PP001-BEGDA =
ZABSF_PP_V_SF001-BEGDA .
ZABSF_PP001-SHIFT_START =
ZABSF_PP_V_SF001-SHIFT_START .
ZABSF_PP001-SHIFT_END =
ZABSF_PP_V_SF001-SHIFT_END .
ZABSF_PP001-FCALID =
ZABSF_PP_V_SF001-FCALID .
ZABSF_PP001-PAUTY =
ZABSF_PP_V_SF001-PAUTY .
ZABSF_PP001-SHIFT_DOWN =
ZABSF_PP_V_SF001-SHIFT_DOWN .
ZABSF_PP001-SHIFT_UP =
ZABSF_PP_V_SF001-SHIFT_UP .
ZABSF_PP001-HOURS_CHG =
ZABSF_PP_V_SF001-HOURS_CHG .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP001 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP001 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP001_T WHERE
    AREAID = ZABSF_PP001-AREAID AND
    WERKS = ZABSF_PP001-WERKS AND
    SHIFTID = ZABSF_PP001-SHIFTID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP001_T.
ZABSF_PP001_T-AREAID =
ZABSF_PP001-AREAID .
ZABSF_PP001_T-WERKS =
ZABSF_PP001-WERKS .
ZABSF_PP001_T-SHIFTID =
ZABSF_PP001-SHIFTID .
ZABSF_PP001_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP001_T-SHIFT_DESC =
ZABSF_PP_V_SF001-SHIFT_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP001_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP001_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF001-UPD_FLAG,
STATUS_ZABSF_PP_V_SF001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF001.
  SELECT SINGLE * FROM ZABSF_PP001 WHERE
AREAID = ZABSF_PP_V_SF001-AREAID AND
WERKS = ZABSF_PP_V_SF001-WERKS AND
SHIFTID = ZABSF_PP_V_SF001-SHIFTID AND
ENDDA = ZABSF_PP_V_SF001-ENDDA .
ZABSF_PP_V_SF001-MANDT =
ZABSF_PP001-MANDT .
ZABSF_PP_V_SF001-AREAID =
ZABSF_PP001-AREAID .
ZABSF_PP_V_SF001-WERKS =
ZABSF_PP001-WERKS .
ZABSF_PP_V_SF001-SHIFTID =
ZABSF_PP001-SHIFTID .
ZABSF_PP_V_SF001-ENDDA =
ZABSF_PP001-ENDDA .
ZABSF_PP_V_SF001-BEGDA =
ZABSF_PP001-BEGDA .
ZABSF_PP_V_SF001-SHIFT_START =
ZABSF_PP001-SHIFT_START .
ZABSF_PP_V_SF001-SHIFT_END =
ZABSF_PP001-SHIFT_END .
ZABSF_PP_V_SF001-FCALID =
ZABSF_PP001-FCALID .
ZABSF_PP_V_SF001-PAUTY =
ZABSF_PP001-PAUTY .
ZABSF_PP_V_SF001-SHIFT_DOWN =
ZABSF_PP001-SHIFT_DOWN .
ZABSF_PP_V_SF001-SHIFT_UP =
ZABSF_PP001-SHIFT_UP .
ZABSF_PP_V_SF001-HOURS_CHG =
ZABSF_PP001-HOURS_CHG .
    SELECT SINGLE * FROM ZABSF_PP001_T WHERE
AREAID = ZABSF_PP001-AREAID AND
WERKS = ZABSF_PP001-WERKS AND
SHIFTID = ZABSF_PP001-SHIFTID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF001-SHIFT_DESC =
ZABSF_PP001_T-SHIFT_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF001-SHIFT_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF001-AREAID TO
ZABSF_PP001-AREAID .
MOVE ZABSF_PP_V_SF001-WERKS TO
ZABSF_PP001-WERKS .
MOVE ZABSF_PP_V_SF001-SHIFTID TO
ZABSF_PP001-SHIFTID .
MOVE ZABSF_PP_V_SF001-ENDDA TO
ZABSF_PP001-ENDDA .
MOVE ZABSF_PP_V_SF001-MANDT TO
ZABSF_PP001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP001-AREAID TO
ZABSF_PP001_T-AREAID .
MOVE ZABSF_PP001-WERKS TO
ZABSF_PP001_T-WERKS .
MOVE ZABSF_PP001-SHIFTID TO
ZABSF_PP001_T-SHIFTID .
MOVE SY-LANGU TO
ZABSF_PP001_T-SPRAS .
MOVE ZABSF_PP_V_SF001-MANDT TO
ZABSF_PP001_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP001_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP001_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP001_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
