*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_EQUI.................................*
FORM GET_DATA_ZABSF_PP_V_EQUI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_EQUIPMENTS WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_EQUI .
ZABSF_PP_V_EQUI-MANDT =
ZABSF_EQUIPMENTS-MANDT .
ZABSF_PP_V_EQUI-ID =
ZABSF_EQUIPMENTS-ID .
ZABSF_PP_V_EQUI-AREAID =
ZABSF_EQUIPMENTS-AREAID .
ZABSF_PP_V_EQUI-WORKCENTERID =
ZABSF_EQUIPMENTS-WORKCENTERID .
ZABSF_PP_V_EQUI-EQUIPMENT =
ZABSF_EQUIPMENTS-EQUIPMENT .
<VIM_TOTAL_STRUC> = ZABSF_PP_V_EQUI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_EQUI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_EQUI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_EQUI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_EQUIPMENTS WHERE
  ID = ZABSF_PP_V_EQUI-ID AND
  AREAID = ZABSF_PP_V_EQUI-AREAID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_EQUIPMENTS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_EQUIPMENTS WHERE
  ID = ZABSF_PP_V_EQUI-ID AND
  AREAID = ZABSF_PP_V_EQUI-AREAID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_EQUIPMENTS.
    ENDIF.
ZABSF_EQUIPMENTS-MANDT =
ZABSF_PP_V_EQUI-MANDT .
ZABSF_EQUIPMENTS-ID =
ZABSF_PP_V_EQUI-ID .
ZABSF_EQUIPMENTS-AREAID =
ZABSF_PP_V_EQUI-AREAID .
ZABSF_EQUIPMENTS-WORKCENTERID =
ZABSF_PP_V_EQUI-WORKCENTERID .
ZABSF_EQUIPMENTS-EQUIPMENT =
ZABSF_PP_V_EQUI-EQUIPMENT .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_EQUIPMENTS ##WARN_OK.
    ELSE.
    INSERT ZABSF_EQUIPMENTS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_EQUI-UPD_FLAG,
STATUS_ZABSF_PP_V_EQUI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_EQUI.
  SELECT SINGLE * FROM ZABSF_EQUIPMENTS WHERE
ID = ZABSF_PP_V_EQUI-ID AND
AREAID = ZABSF_PP_V_EQUI-AREAID .
ZABSF_PP_V_EQUI-MANDT =
ZABSF_EQUIPMENTS-MANDT .
ZABSF_PP_V_EQUI-ID =
ZABSF_EQUIPMENTS-ID .
ZABSF_PP_V_EQUI-AREAID =
ZABSF_EQUIPMENTS-AREAID .
ZABSF_PP_V_EQUI-WORKCENTERID =
ZABSF_EQUIPMENTS-WORKCENTERID .
ZABSF_PP_V_EQUI-EQUIPMENT =
ZABSF_EQUIPMENTS-EQUIPMENT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_EQUI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_EQUI-ID TO
ZABSF_EQUIPMENTS-ID .
MOVE ZABSF_PP_V_EQUI-AREAID TO
ZABSF_EQUIPMENTS-AREAID .
MOVE ZABSF_PP_V_EQUI-MANDT TO
ZABSF_EQUIPMENTS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_EQUIPMENTS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_EQUIPMENTS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_EQUIPMENTS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
