*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF021................................*
FORM GET_DATA_ZABSF_PP_V_SF021.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP026 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF021 .
ZABSF_PP_V_SF021-MANDT =
ZABSF_PP026-MANDT .
ZABSF_PP_V_SF021-AREAID =
ZABSF_PP026-AREAID .
ZABSF_PP_V_SF021-WERKS =
ZABSF_PP026-WERKS .
ZABSF_PP_V_SF021-ARBPL =
ZABSF_PP026-ARBPL .
ZABSF_PP_V_SF021-DEFECTID =
ZABSF_PP026-DEFECTID .
ZABSF_PP_V_SF021-PLNNR =
ZABSF_PP026-PLNNR .
    SELECT SINGLE * FROM ZABSF_PP026_T WHERE
AREAID = ZABSF_PP026-AREAID AND
WERKS = ZABSF_PP026-WERKS AND
ARBPL = ZABSF_PP026-ARBPL AND
DEFECTID = ZABSF_PP026-DEFECTID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF021-DEFECT_DESC =
ZABSF_PP026_T-DEFECT_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF021.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF021 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF021.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF021-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP026 WHERE
  AREAID = ZABSF_PP_V_SF021-AREAID AND
  WERKS = ZABSF_PP_V_SF021-WERKS AND
  ARBPL = ZABSF_PP_V_SF021-ARBPL AND
  DEFECTID = ZABSF_PP_V_SF021-DEFECTID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP026 .
    ENDIF.
    DELETE FROM ZABSF_PP026_T WHERE
    AREAID = ZABSF_PP026-AREAID AND
    WERKS = ZABSF_PP026-WERKS AND
    ARBPL = ZABSF_PP026-ARBPL AND
    DEFECTID = ZABSF_PP026-DEFECTID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP026 WHERE
  AREAID = ZABSF_PP_V_SF021-AREAID AND
  WERKS = ZABSF_PP_V_SF021-WERKS AND
  ARBPL = ZABSF_PP_V_SF021-ARBPL AND
  DEFECTID = ZABSF_PP_V_SF021-DEFECTID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP026.
    ENDIF.
ZABSF_PP026-MANDT =
ZABSF_PP_V_SF021-MANDT .
ZABSF_PP026-AREAID =
ZABSF_PP_V_SF021-AREAID .
ZABSF_PP026-WERKS =
ZABSF_PP_V_SF021-WERKS .
ZABSF_PP026-ARBPL =
ZABSF_PP_V_SF021-ARBPL .
ZABSF_PP026-DEFECTID =
ZABSF_PP_V_SF021-DEFECTID .
ZABSF_PP026-PLNNR =
ZABSF_PP_V_SF021-PLNNR .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP026 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP026 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP026_T WHERE
    AREAID = ZABSF_PP026-AREAID AND
    WERKS = ZABSF_PP026-WERKS AND
    ARBPL = ZABSF_PP026-ARBPL AND
    DEFECTID = ZABSF_PP026-DEFECTID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP026_T.
ZABSF_PP026_T-AREAID =
ZABSF_PP026-AREAID .
ZABSF_PP026_T-WERKS =
ZABSF_PP026-WERKS .
ZABSF_PP026_T-ARBPL =
ZABSF_PP026-ARBPL .
ZABSF_PP026_T-DEFECTID =
ZABSF_PP026-DEFECTID .
ZABSF_PP026_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP026_T-DEFECT_DESC =
ZABSF_PP_V_SF021-DEFECT_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP026_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP026_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF021-UPD_FLAG,
STATUS_ZABSF_PP_V_SF021-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF021.
  SELECT SINGLE * FROM ZABSF_PP026 WHERE
AREAID = ZABSF_PP_V_SF021-AREAID AND
WERKS = ZABSF_PP_V_SF021-WERKS AND
ARBPL = ZABSF_PP_V_SF021-ARBPL AND
DEFECTID = ZABSF_PP_V_SF021-DEFECTID .
ZABSF_PP_V_SF021-MANDT =
ZABSF_PP026-MANDT .
ZABSF_PP_V_SF021-AREAID =
ZABSF_PP026-AREAID .
ZABSF_PP_V_SF021-WERKS =
ZABSF_PP026-WERKS .
ZABSF_PP_V_SF021-ARBPL =
ZABSF_PP026-ARBPL .
ZABSF_PP_V_SF021-DEFECTID =
ZABSF_PP026-DEFECTID .
ZABSF_PP_V_SF021-PLNNR =
ZABSF_PP026-PLNNR .
    SELECT SINGLE * FROM ZABSF_PP026_T WHERE
AREAID = ZABSF_PP026-AREAID AND
WERKS = ZABSF_PP026-WERKS AND
ARBPL = ZABSF_PP026-ARBPL AND
DEFECTID = ZABSF_PP026-DEFECTID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF021-DEFECT_DESC =
ZABSF_PP026_T-DEFECT_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF021-DEFECT_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF021 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF021-AREAID TO
ZABSF_PP026-AREAID .
MOVE ZABSF_PP_V_SF021-WERKS TO
ZABSF_PP026-WERKS .
MOVE ZABSF_PP_V_SF021-ARBPL TO
ZABSF_PP026-ARBPL .
MOVE ZABSF_PP_V_SF021-DEFECTID TO
ZABSF_PP026-DEFECTID .
MOVE ZABSF_PP_V_SF021-MANDT TO
ZABSF_PP026-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP026'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP026 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP026'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP026-AREAID TO
ZABSF_PP026_T-AREAID .
MOVE ZABSF_PP026-WERKS TO
ZABSF_PP026_T-WERKS .
MOVE ZABSF_PP026-ARBPL TO
ZABSF_PP026_T-ARBPL .
MOVE ZABSF_PP026-DEFECTID TO
ZABSF_PP026_T-DEFECTID .
MOVE SY-LANGU TO
ZABSF_PP026_T-SPRAS .
MOVE ZABSF_PP_V_SF021-MANDT TO
ZABSF_PP026_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP026_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP026_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP026_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
