*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF023................................*
FORM GET_DATA_ZABSF_PP_V_SF023.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP029 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF023 .
ZABSF_PP_V_SF023-MANDT =
ZABSF_PP029-MANDT .
ZABSF_PP_V_SF023-WERKS =
ZABSF_PP029-WERKS .
ZABSF_PP_V_SF023-ARBPL =
ZABSF_PP029-ARBPL .
ZABSF_PP_V_SF023-MATNR =
ZABSF_PP029-MATNR .
ZABSF_PP_V_SF023-MEASEUREID =
ZABSF_PP029-MEASEUREID .
ZABSF_PP_V_SF023-ENDDA =
ZABSF_PP029-ENDDA .
ZABSF_PP_V_SF023-BEGDA =
ZABSF_PP029-BEGDA .
    SELECT SINGLE * FROM ZABSF_PP029_T WHERE
WERKS = ZABSF_PP029-WERKS AND
ARBPL = ZABSF_PP029-ARBPL AND
MATNR = ZABSF_PP029-MATNR AND
MEASEUREID = ZABSF_PP029-MEASEUREID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF023-MEASEURE_DESC =
ZABSF_PP029_T-MEASEURE_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF023.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF023 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF023.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF023-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP029 WHERE
  WERKS = ZABSF_PP_V_SF023-WERKS AND
  ARBPL = ZABSF_PP_V_SF023-ARBPL AND
  MATNR = ZABSF_PP_V_SF023-MATNR AND
  ENDDA = ZABSF_PP_V_SF023-ENDDA AND
  MEASEUREID = ZABSF_PP_V_SF023-MEASEUREID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP029 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP029_T WHERE
    WERKS = ZABSF_PP029-WERKS AND
    ARBPL = ZABSF_PP029-ARBPL AND
    MATNR = ZABSF_PP029-MATNR AND
    MEASEUREID = ZABSF_PP029-MEASEUREID AND
    SPRAS = SY-LANGU .
    IF SY-SUBRC = 0.
    SELECT COUNT(*) FROM ZABSF_PP029 WHERE
    WERKS EQ ZABSF_PP029_T-WERKS AND
    ARBPL EQ ZABSF_PP029_T-ARBPL AND
    MATNR EQ ZABSF_PP029_T-MATNR AND
    MEASEUREID EQ ZABSF_PP029_T-MEASEUREID .
      IF SY-DBCNT EQ 0.
    DELETE FROM ZABSF_PP029_T WHERE
    WERKS = ZABSF_PP029-WERKS AND
    ARBPL = ZABSF_PP029-ARBPL AND
    MATNR = ZABSF_PP029-MATNR AND
    MEASEUREID = ZABSF_PP029-MEASEUREID .
      ENDIF.
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP029 WHERE
  WERKS = ZABSF_PP_V_SF023-WERKS AND
  ARBPL = ZABSF_PP_V_SF023-ARBPL AND
  MATNR = ZABSF_PP_V_SF023-MATNR AND
  ENDDA = ZABSF_PP_V_SF023-ENDDA AND
  MEASEUREID = ZABSF_PP_V_SF023-MEASEUREID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP029.
    ENDIF.
ZABSF_PP029-MANDT =
ZABSF_PP_V_SF023-MANDT .
ZABSF_PP029-WERKS =
ZABSF_PP_V_SF023-WERKS .
ZABSF_PP029-ARBPL =
ZABSF_PP_V_SF023-ARBPL .
ZABSF_PP029-MATNR =
ZABSF_PP_V_SF023-MATNR .
ZABSF_PP029-MEASEUREID =
ZABSF_PP_V_SF023-MEASEUREID .
ZABSF_PP029-ENDDA =
ZABSF_PP_V_SF023-ENDDA .
ZABSF_PP029-BEGDA =
ZABSF_PP_V_SF023-BEGDA .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP029 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP029 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP029_T WHERE
    WERKS = ZABSF_PP029-WERKS AND
    ARBPL = ZABSF_PP029-ARBPL AND
    MATNR = ZABSF_PP029-MATNR AND
    MEASEUREID = ZABSF_PP029-MEASEUREID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP029_T.
ZABSF_PP029_T-WERKS =
ZABSF_PP029-WERKS .
ZABSF_PP029_T-ARBPL =
ZABSF_PP029-ARBPL .
ZABSF_PP029_T-MATNR =
ZABSF_PP029-MATNR .
ZABSF_PP029_T-MEASEUREID =
ZABSF_PP029-MEASEUREID .
ZABSF_PP029_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP029_T-MEASEURE_DESC =
ZABSF_PP_V_SF023-MEASEURE_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP029_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP029_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF023-UPD_FLAG,
STATUS_ZABSF_PP_V_SF023-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF023.
  SELECT SINGLE * FROM ZABSF_PP029 WHERE
WERKS = ZABSF_PP_V_SF023-WERKS AND
ARBPL = ZABSF_PP_V_SF023-ARBPL AND
MATNR = ZABSF_PP_V_SF023-MATNR AND
ENDDA = ZABSF_PP_V_SF023-ENDDA AND
MEASEUREID = ZABSF_PP_V_SF023-MEASEUREID .
ZABSF_PP_V_SF023-MANDT =
ZABSF_PP029-MANDT .
ZABSF_PP_V_SF023-WERKS =
ZABSF_PP029-WERKS .
ZABSF_PP_V_SF023-ARBPL =
ZABSF_PP029-ARBPL .
ZABSF_PP_V_SF023-MATNR =
ZABSF_PP029-MATNR .
ZABSF_PP_V_SF023-MEASEUREID =
ZABSF_PP029-MEASEUREID .
ZABSF_PP_V_SF023-ENDDA =
ZABSF_PP029-ENDDA .
ZABSF_PP_V_SF023-BEGDA =
ZABSF_PP029-BEGDA .
    SELECT SINGLE * FROM ZABSF_PP029_T WHERE
WERKS = ZABSF_PP029-WERKS AND
ARBPL = ZABSF_PP029-ARBPL AND
MATNR = ZABSF_PP029-MATNR AND
MEASEUREID = ZABSF_PP029-MEASEUREID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF023-MEASEURE_DESC =
ZABSF_PP029_T-MEASEURE_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF023-MEASEURE_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF023 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF023-WERKS TO
ZABSF_PP029-WERKS .
MOVE ZABSF_PP_V_SF023-ARBPL TO
ZABSF_PP029-ARBPL .
MOVE ZABSF_PP_V_SF023-MATNR TO
ZABSF_PP029-MATNR .
MOVE ZABSF_PP_V_SF023-ENDDA TO
ZABSF_PP029-ENDDA .
MOVE ZABSF_PP_V_SF023-MEASEUREID TO
ZABSF_PP029-MEASEUREID .
MOVE ZABSF_PP_V_SF023-MANDT TO
ZABSF_PP029-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP029'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP029 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP029'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP029-WERKS TO
ZABSF_PP029_T-WERKS .
MOVE ZABSF_PP029-ARBPL TO
ZABSF_PP029_T-ARBPL .
MOVE ZABSF_PP029-MATNR TO
ZABSF_PP029_T-MATNR .
MOVE ZABSF_PP029-MEASEUREID TO
ZABSF_PP029_T-MEASEUREID .
MOVE SY-LANGU TO
ZABSF_PP029_T-SPRAS .
MOVE ZABSF_PP_V_SF023-MANDT TO
ZABSF_PP029_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP029_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP029_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP029_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
