*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF078................................*
FORM GET_DATA_ZABSF_PP_V_SF078.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP078 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF078 .
ZABSF_PP_V_SF078-MANDT =
ZABSF_PP078-MANDT .
ZABSF_PP_V_SF078-WERKS =
ZABSF_PP078-WERKS .
ZABSF_PP_V_SF078-CHARG =
ZABSF_PP078-CHARG .
ZABSF_PP_V_SF078-VALIDATION_DATE =
ZABSF_PP078-VALIDATION_DATE .
ZABSF_PP_V_SF078-VALID_DAYS =
ZABSF_PP078-VALID_DAYS .
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF078.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF078 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF078.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF078-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP078 WHERE
  WERKS = ZABSF_PP_V_SF078-WERKS AND
  CHARG = ZABSF_PP_V_SF078-CHARG AND
  VALIDATION_DATE = ZABSF_PP_V_SF078-VALIDATION_DATE .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP078 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP078 WHERE
  WERKS = ZABSF_PP_V_SF078-WERKS AND
  CHARG = ZABSF_PP_V_SF078-CHARG AND
  VALIDATION_DATE = ZABSF_PP_V_SF078-VALIDATION_DATE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP078.
    ENDIF.
ZABSF_PP078-MANDT =
ZABSF_PP_V_SF078-MANDT .
ZABSF_PP078-WERKS =
ZABSF_PP_V_SF078-WERKS .
ZABSF_PP078-CHARG =
ZABSF_PP_V_SF078-CHARG .
ZABSF_PP078-VALIDATION_DATE =
ZABSF_PP_V_SF078-VALIDATION_DATE .
ZABSF_PP078-VALID_DAYS =
ZABSF_PP_V_SF078-VALID_DAYS .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP078 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP078 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF078-UPD_FLAG,
STATUS_ZABSF_PP_V_SF078-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF078.
  SELECT SINGLE * FROM ZABSF_PP078 WHERE
WERKS = ZABSF_PP_V_SF078-WERKS AND
CHARG = ZABSF_PP_V_SF078-CHARG AND
VALIDATION_DATE = ZABSF_PP_V_SF078-VALIDATION_DATE .
ZABSF_PP_V_SF078-MANDT =
ZABSF_PP078-MANDT .
ZABSF_PP_V_SF078-WERKS =
ZABSF_PP078-WERKS .
ZABSF_PP_V_SF078-CHARG =
ZABSF_PP078-CHARG .
ZABSF_PP_V_SF078-VALIDATION_DATE =
ZABSF_PP078-VALIDATION_DATE .
ZABSF_PP_V_SF078-VALID_DAYS =
ZABSF_PP078-VALID_DAYS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF078 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF078-WERKS TO
ZABSF_PP078-WERKS .
MOVE ZABSF_PP_V_SF078-CHARG TO
ZABSF_PP078-CHARG .
MOVE ZABSF_PP_V_SF078-VALIDATION_DATE TO
ZABSF_PP078-VALIDATION_DATE .
MOVE ZABSF_PP_V_SF078-MANDT TO
ZABSF_PP078-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP078'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP078 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP078'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
