*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF047................................*
FORM GET_DATA_ZABSF_PP_V_SF047.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP072 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF047 .
ZABSF_PP_V_SF047-MANDT =
ZABSF_PP072-MANDT .
ZABSF_PP_V_SF047-WERKS =
ZABSF_PP072-WERKS .
ZABSF_PP_V_SF047-AREA =
ZABSF_PP072-AREA .
ZABSF_PP_V_SF047-DEFECTID =
ZABSF_PP072-DEFECTID .
    SELECT SINGLE * FROM TC24 WHERE
WERKS = ZABSF_PP072-WERKS AND
VERAN = ZABSF_PP072-AREA .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-KTEXT =
TC24-KTEXT .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = ZABSF_PP072-WERKS AND
GRUND = ZABSF_PP072-DEFECTID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-GRDTX =
TRUGT-GRDTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF047.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF047 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF047.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF047-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP072 WHERE
  WERKS = ZABSF_PP_V_SF047-WERKS AND
  DEFECTID = ZABSF_PP_V_SF047-DEFECTID AND
  AREA = ZABSF_PP_V_SF047-AREA .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP072 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP072 WHERE
  WERKS = ZABSF_PP_V_SF047-WERKS AND
  DEFECTID = ZABSF_PP_V_SF047-DEFECTID AND
  AREA = ZABSF_PP_V_SF047-AREA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP072.
    ENDIF.
ZABSF_PP072-MANDT =
ZABSF_PP_V_SF047-MANDT .
ZABSF_PP072-WERKS =
ZABSF_PP_V_SF047-WERKS .
ZABSF_PP072-AREA =
ZABSF_PP_V_SF047-AREA .
ZABSF_PP072-DEFECTID =
ZABSF_PP_V_SF047-DEFECTID .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP072 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP072 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF047-UPD_FLAG,
STATUS_ZABSF_PP_V_SF047-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF047.
  SELECT SINGLE * FROM ZABSF_PP072 WHERE
WERKS = ZABSF_PP_V_SF047-WERKS AND
DEFECTID = ZABSF_PP_V_SF047-DEFECTID AND
AREA = ZABSF_PP_V_SF047-AREA .
ZABSF_PP_V_SF047-MANDT =
ZABSF_PP072-MANDT .
ZABSF_PP_V_SF047-WERKS =
ZABSF_PP072-WERKS .
ZABSF_PP_V_SF047-AREA =
ZABSF_PP072-AREA .
ZABSF_PP_V_SF047-DEFECTID =
ZABSF_PP072-DEFECTID .
    SELECT SINGLE * FROM TC24 WHERE
WERKS = ZABSF_PP072-WERKS AND
VERAN = ZABSF_PP072-AREA .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-KTEXT =
TC24-KTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF047-KTEXT .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = ZABSF_PP072-WERKS AND
GRUND = ZABSF_PP072-DEFECTID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-GRDTX =
TRUGT-GRDTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSF_PP_V_SF047-GRDTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF047-GRDTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF047 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF047-WERKS TO
ZABSF_PP072-WERKS .
MOVE ZABSF_PP_V_SF047-DEFECTID TO
ZABSF_PP072-DEFECTID .
MOVE ZABSF_PP_V_SF047-AREA TO
ZABSF_PP072-AREA .
MOVE ZABSF_PP_V_SF047-MANDT TO
ZABSF_PP072-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP072'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP072 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP072'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZABSF_PP_V_SF047 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZABSF_PP072-MANDT =
ZABSF_PP_V_SF047-MANDT .
ZABSF_PP072-WERKS =
ZABSF_PP_V_SF047-WERKS .
ZABSF_PP072-AREA =
ZABSF_PP_V_SF047-AREA .
ZABSF_PP072-DEFECTID =
ZABSF_PP_V_SF047-DEFECTID .
    SELECT SINGLE * FROM TC24 WHERE
WERKS = ZABSF_PP072-WERKS AND
VERAN = ZABSF_PP072-AREA .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-KTEXT =
TC24-KTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF047-KTEXT .
    ENDIF.
    SELECT SINGLE * FROM TRUG WHERE
WERKS = ZABSF_PP072-WERKS AND
GRUND = ZABSF_PP072-DEFECTID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TRUGT WHERE
WERKS = TRUG-WERKS AND
GRUND = TRUG-GRUND AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF047-GRDTX =
TRUGT-GRDTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSF_PP_V_SF047-GRDTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF047-GRDTX .
    ENDIF.
ENDFORM.
