*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF003................................*
FORM GET_DATA_ZABSF_PP_V_SF003.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP003 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF003 .
ZABSF_PP_V_SF003-MANDT =
ZABSF_PP003-MANDT .
ZABSF_PP_V_SF003-ID_CLASS =
ZABSF_PP003-ID_CLASS .
ZABSF_PP_V_SF003-WERKS =
ZABSF_PP003-WERKS .
ZABSF_PP_V_SF003-ENDDA =
ZABSF_PP003-ENDDA .
ZABSF_PP_V_SF003-BEGDA =
ZABSF_PP003-BEGDA .
ZABSF_PP_V_SF003-IMP_CLNAME =
ZABSF_PP003-IMP_CLNAME .
ZABSF_PP_V_SF003-METHODNAME =
ZABSF_PP003-METHODNAME .
    SELECT SINGLE * FROM ZABSF_PP003_T WHERE
ID_CLASS = ZABSF_PP003-ID_CLASS AND
WERKS = ZABSF_PP003-WERKS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF003-CLASS_DESC =
ZABSF_PP003_T-CLASS_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF003.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF003 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF003.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF003-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP003 WHERE
  ID_CLASS = ZABSF_PP_V_SF003-ID_CLASS AND
  WERKS = ZABSF_PP_V_SF003-WERKS AND
  ENDDA = ZABSF_PP_V_SF003-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP003 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP003_T WHERE
    ID_CLASS = ZABSF_PP003-ID_CLASS AND
    WERKS = ZABSF_PP003-WERKS AND
    SPRAS = SY-LANGU .
    IF SY-SUBRC = 0.
    SELECT COUNT(*) FROM ZABSF_PP003 WHERE
    ID_CLASS EQ ZABSF_PP003_T-ID_CLASS AND
    WERKS EQ ZABSF_PP003_T-WERKS .
      IF SY-DBCNT EQ 0.
    DELETE FROM ZABSF_PP003_T WHERE
    ID_CLASS = ZABSF_PP003-ID_CLASS AND
    WERKS = ZABSF_PP003-WERKS .
      ENDIF.
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP003 WHERE
  ID_CLASS = ZABSF_PP_V_SF003-ID_CLASS AND
  WERKS = ZABSF_PP_V_SF003-WERKS AND
  ENDDA = ZABSF_PP_V_SF003-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP003.
    ENDIF.
ZABSF_PP003-MANDT =
ZABSF_PP_V_SF003-MANDT .
ZABSF_PP003-ID_CLASS =
ZABSF_PP_V_SF003-ID_CLASS .
ZABSF_PP003-WERKS =
ZABSF_PP_V_SF003-WERKS .
ZABSF_PP003-ENDDA =
ZABSF_PP_V_SF003-ENDDA .
ZABSF_PP003-BEGDA =
ZABSF_PP_V_SF003-BEGDA .
ZABSF_PP003-IMP_CLNAME =
ZABSF_PP_V_SF003-IMP_CLNAME .
ZABSF_PP003-METHODNAME =
ZABSF_PP_V_SF003-METHODNAME .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP003 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP003 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP003_T WHERE
    ID_CLASS = ZABSF_PP003-ID_CLASS AND
    WERKS = ZABSF_PP003-WERKS AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP003_T.
ZABSF_PP003_T-ID_CLASS =
ZABSF_PP003-ID_CLASS .
ZABSF_PP003_T-WERKS =
ZABSF_PP003-WERKS .
ZABSF_PP003_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP003_T-CLASS_DESC =
ZABSF_PP_V_SF003-CLASS_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP003_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP003_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF003-UPD_FLAG,
STATUS_ZABSF_PP_V_SF003-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF003.
  SELECT SINGLE * FROM ZABSF_PP003 WHERE
ID_CLASS = ZABSF_PP_V_SF003-ID_CLASS AND
WERKS = ZABSF_PP_V_SF003-WERKS AND
ENDDA = ZABSF_PP_V_SF003-ENDDA .
ZABSF_PP_V_SF003-MANDT =
ZABSF_PP003-MANDT .
ZABSF_PP_V_SF003-ID_CLASS =
ZABSF_PP003-ID_CLASS .
ZABSF_PP_V_SF003-WERKS =
ZABSF_PP003-WERKS .
ZABSF_PP_V_SF003-ENDDA =
ZABSF_PP003-ENDDA .
ZABSF_PP_V_SF003-BEGDA =
ZABSF_PP003-BEGDA .
ZABSF_PP_V_SF003-IMP_CLNAME =
ZABSF_PP003-IMP_CLNAME .
ZABSF_PP_V_SF003-METHODNAME =
ZABSF_PP003-METHODNAME .
    SELECT SINGLE * FROM ZABSF_PP003_T WHERE
ID_CLASS = ZABSF_PP003-ID_CLASS AND
WERKS = ZABSF_PP003-WERKS AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF003-CLASS_DESC =
ZABSF_PP003_T-CLASS_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF003-CLASS_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF003 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF003-ID_CLASS TO
ZABSF_PP003-ID_CLASS .
MOVE ZABSF_PP_V_SF003-WERKS TO
ZABSF_PP003-WERKS .
MOVE ZABSF_PP_V_SF003-ENDDA TO
ZABSF_PP003-ENDDA .
MOVE ZABSF_PP_V_SF003-MANDT TO
ZABSF_PP003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP003-ID_CLASS TO
ZABSF_PP003_T-ID_CLASS .
MOVE ZABSF_PP003-WERKS TO
ZABSF_PP003_T-WERKS .
MOVE SY-LANGU TO
ZABSF_PP003_T-SPRAS .
MOVE ZABSF_PP_V_SF003-MANDT TO
ZABSF_PP003_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP003_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP003_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP003_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
