*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF038................................*
FORM GET_DATA_ZABSF_PP_V_SF038.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP057 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF038 .
ZABSF_PP_V_SF038-MANDT =
ZABSF_PP057-MANDT .
ZABSF_PP_V_SF038-AREAID =
ZABSF_PP057-AREAID .
ZABSF_PP_V_SF038-WAREID =
ZABSF_PP057-WAREID .
ZABSF_PP_V_SF038-MATNR =
ZABSF_PP057-MATNR .
ZABSF_PP_V_SF038-DATA =
ZABSF_PP057-DATA .
ZABSF_PP_V_SF038-TIME =
ZABSF_PP057-TIME .
ZABSF_PP_V_SF038-OPRID =
ZABSF_PP057-OPRID .
ZABSF_PP_V_SF038-ZCNTRL =
ZABSF_PP057-ZCNTRL .
ZABSF_PP_V_SF038-LMNGA =
ZABSF_PP057-LMNGA .
ZABSF_PP_V_SF038-GMEIN =
ZABSF_PP057-GMEIN .
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF038.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF038 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF038.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF038-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP057 WHERE
  AREAID = ZABSF_PP_V_SF038-AREAID AND
  WAREID = ZABSF_PP_V_SF038-WAREID AND
  MATNR = ZABSF_PP_V_SF038-MATNR AND
  DATA = ZABSF_PP_V_SF038-DATA AND
  TIME = ZABSF_PP_V_SF038-TIME AND
  OPRID = ZABSF_PP_V_SF038-OPRID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP057 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP057 WHERE
  AREAID = ZABSF_PP_V_SF038-AREAID AND
  WAREID = ZABSF_PP_V_SF038-WAREID AND
  MATNR = ZABSF_PP_V_SF038-MATNR AND
  DATA = ZABSF_PP_V_SF038-DATA AND
  TIME = ZABSF_PP_V_SF038-TIME AND
  OPRID = ZABSF_PP_V_SF038-OPRID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP057.
    ENDIF.
ZABSF_PP057-MANDT =
ZABSF_PP_V_SF038-MANDT .
ZABSF_PP057-AREAID =
ZABSF_PP_V_SF038-AREAID .
ZABSF_PP057-WAREID =
ZABSF_PP_V_SF038-WAREID .
ZABSF_PP057-MATNR =
ZABSF_PP_V_SF038-MATNR .
ZABSF_PP057-DATA =
ZABSF_PP_V_SF038-DATA .
ZABSF_PP057-TIME =
ZABSF_PP_V_SF038-TIME .
ZABSF_PP057-OPRID =
ZABSF_PP_V_SF038-OPRID .
ZABSF_PP057-ZCNTRL =
ZABSF_PP_V_SF038-ZCNTRL .
ZABSF_PP057-LMNGA =
ZABSF_PP_V_SF038-LMNGA .
ZABSF_PP057-GMEIN =
ZABSF_PP_V_SF038-GMEIN .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP057 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP057 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF038-UPD_FLAG,
STATUS_ZABSF_PP_V_SF038-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF038.
  SELECT SINGLE * FROM ZABSF_PP057 WHERE
AREAID = ZABSF_PP_V_SF038-AREAID AND
WAREID = ZABSF_PP_V_SF038-WAREID AND
MATNR = ZABSF_PP_V_SF038-MATNR AND
DATA = ZABSF_PP_V_SF038-DATA AND
TIME = ZABSF_PP_V_SF038-TIME AND
OPRID = ZABSF_PP_V_SF038-OPRID .
ZABSF_PP_V_SF038-MANDT =
ZABSF_PP057-MANDT .
ZABSF_PP_V_SF038-AREAID =
ZABSF_PP057-AREAID .
ZABSF_PP_V_SF038-WAREID =
ZABSF_PP057-WAREID .
ZABSF_PP_V_SF038-MATNR =
ZABSF_PP057-MATNR .
ZABSF_PP_V_SF038-DATA =
ZABSF_PP057-DATA .
ZABSF_PP_V_SF038-TIME =
ZABSF_PP057-TIME .
ZABSF_PP_V_SF038-OPRID =
ZABSF_PP057-OPRID .
ZABSF_PP_V_SF038-ZCNTRL =
ZABSF_PP057-ZCNTRL .
ZABSF_PP_V_SF038-LMNGA =
ZABSF_PP057-LMNGA .
ZABSF_PP_V_SF038-GMEIN =
ZABSF_PP057-GMEIN .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF038 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF038-AREAID TO
ZABSF_PP057-AREAID .
MOVE ZABSF_PP_V_SF038-WAREID TO
ZABSF_PP057-WAREID .
MOVE ZABSF_PP_V_SF038-MATNR TO
ZABSF_PP057-MATNR .
MOVE ZABSF_PP_V_SF038-DATA TO
ZABSF_PP057-DATA .
MOVE ZABSF_PP_V_SF038-TIME TO
ZABSF_PP057-TIME .
MOVE ZABSF_PP_V_SF038-OPRID TO
ZABSF_PP057-OPRID .
MOVE ZABSF_PP_V_SF038-MANDT TO
ZABSF_PP057-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP057'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP057 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP057'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
