*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF079................................*
FORM GET_DATA_ZABSF_PP_V_SF079.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP079 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF079 .
ZABSF_PP_V_SF079-MANDT =
ZABSF_PP079-MANDT .
ZABSF_PP_V_SF079-WERKS =
ZABSF_PP079-WERKS .
ZABSF_PP_V_SF079-AREAID =
ZABSF_PP079-AREAID .
ZABSF_PP_V_SF079-PARID =
ZABSF_PP079-PARID .
ZABSF_PP_V_SF079-STATUS =
ZABSF_PP079-STATUS .
    SELECT SINGLE * FROM ZABSF_PP079_T WHERE
WERKS = ZABSF_PP079-WERKS AND
AREAID = ZABSF_PP079-AREAID AND
PARID = ZABSF_PP079-PARID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF079-DESCRIPTION =
ZABSF_PP079_T-DESCRIPTION .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF079.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF079 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF079.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF079-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP079 WHERE
  WERKS = ZABSF_PP_V_SF079-WERKS AND
  AREAID = ZABSF_PP_V_SF079-AREAID AND
  PARID = ZABSF_PP_V_SF079-PARID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP079 .
    ENDIF.
    DELETE FROM ZABSF_PP079_T WHERE
    WERKS = ZABSF_PP079-WERKS AND
    AREAID = ZABSF_PP079-AREAID AND
    PARID = ZABSF_PP079-PARID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP079 WHERE
  WERKS = ZABSF_PP_V_SF079-WERKS AND
  AREAID = ZABSF_PP_V_SF079-AREAID AND
  PARID = ZABSF_PP_V_SF079-PARID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP079.
    ENDIF.
ZABSF_PP079-MANDT =
ZABSF_PP_V_SF079-MANDT .
ZABSF_PP079-WERKS =
ZABSF_PP_V_SF079-WERKS .
ZABSF_PP079-AREAID =
ZABSF_PP_V_SF079-AREAID .
ZABSF_PP079-PARID =
ZABSF_PP_V_SF079-PARID .
ZABSF_PP079-STATUS =
ZABSF_PP_V_SF079-STATUS .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP079 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP079 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP079_T WHERE
    WERKS = ZABSF_PP079-WERKS AND
    AREAID = ZABSF_PP079-AREAID AND
    PARID = ZABSF_PP079-PARID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP079_T.
ZABSF_PP079_T-WERKS =
ZABSF_PP079-WERKS .
ZABSF_PP079_T-AREAID =
ZABSF_PP079-AREAID .
ZABSF_PP079_T-PARID =
ZABSF_PP079-PARID .
ZABSF_PP079_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP079_T-DESCRIPTION =
ZABSF_PP_V_SF079-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP079_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP079_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF079-UPD_FLAG,
STATUS_ZABSF_PP_V_SF079-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF079.
  SELECT SINGLE * FROM ZABSF_PP079 WHERE
WERKS = ZABSF_PP_V_SF079-WERKS AND
AREAID = ZABSF_PP_V_SF079-AREAID AND
PARID = ZABSF_PP_V_SF079-PARID .
ZABSF_PP_V_SF079-MANDT =
ZABSF_PP079-MANDT .
ZABSF_PP_V_SF079-WERKS =
ZABSF_PP079-WERKS .
ZABSF_PP_V_SF079-AREAID =
ZABSF_PP079-AREAID .
ZABSF_PP_V_SF079-PARID =
ZABSF_PP079-PARID .
ZABSF_PP_V_SF079-STATUS =
ZABSF_PP079-STATUS .
    SELECT SINGLE * FROM ZABSF_PP079_T WHERE
WERKS = ZABSF_PP079-WERKS AND
AREAID = ZABSF_PP079-AREAID AND
PARID = ZABSF_PP079-PARID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF079-DESCRIPTION =
ZABSF_PP079_T-DESCRIPTION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF079-DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF079 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF079-WERKS TO
ZABSF_PP079-WERKS .
MOVE ZABSF_PP_V_SF079-AREAID TO
ZABSF_PP079-AREAID .
MOVE ZABSF_PP_V_SF079-PARID TO
ZABSF_PP079-PARID .
MOVE ZABSF_PP_V_SF079-MANDT TO
ZABSF_PP079-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP079'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP079 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP079'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP079-WERKS TO
ZABSF_PP079_T-WERKS .
MOVE ZABSF_PP079-AREAID TO
ZABSF_PP079_T-AREAID .
MOVE ZABSF_PP079-PARID TO
ZABSF_PP079_T-PARID .
MOVE SY-LANGU TO
ZABSF_PP079_T-SPRAS .
MOVE ZABSF_PP_V_SF079-MANDT TO
ZABSF_PP079_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP079_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP079_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP079_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
