*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF024................................*
FORM GET_DATA_ZABSF_PP_V_SF024.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP032 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF024 .
ZABSF_PP_V_SF024-MANDT =
ZABSF_PP032-MANDT .
ZABSF_PP_V_SF024-WERKS =
ZABSF_PP032-WERKS .
ZABSF_PP_V_SF024-PARID =
ZABSF_PP032-PARID .
ZABSF_PP_V_SF024-PARVA =
ZABSF_PP032-PARVA .
    SELECT SINGLE * FROM ZABSF_PP032_T WHERE
WERKS = ZABSF_PP032-WERKS AND
PARID = ZABSF_PP032-PARID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF024-PARTXT =
ZABSF_PP032_T-PARTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF024.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF024 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF024.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF024-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP032 WHERE
  WERKS = ZABSF_PP_V_SF024-WERKS AND
  PARID = ZABSF_PP_V_SF024-PARID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP032 .
    ENDIF.
    DELETE FROM ZABSF_PP032_T WHERE
    WERKS = ZABSF_PP032-WERKS AND
    PARID = ZABSF_PP032-PARID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP032 WHERE
  WERKS = ZABSF_PP_V_SF024-WERKS AND
  PARID = ZABSF_PP_V_SF024-PARID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP032.
    ENDIF.
ZABSF_PP032-MANDT =
ZABSF_PP_V_SF024-MANDT .
ZABSF_PP032-WERKS =
ZABSF_PP_V_SF024-WERKS .
ZABSF_PP032-PARID =
ZABSF_PP_V_SF024-PARID .
ZABSF_PP032-PARVA =
ZABSF_PP_V_SF024-PARVA .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP032 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP032 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP032_T WHERE
    WERKS = ZABSF_PP032-WERKS AND
    PARID = ZABSF_PP032-PARID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP032_T.
ZABSF_PP032_T-WERKS =
ZABSF_PP032-WERKS .
ZABSF_PP032_T-PARID =
ZABSF_PP032-PARID .
ZABSF_PP032_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP032_T-PARTXT =
ZABSF_PP_V_SF024-PARTXT .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP032_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP032_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF024-UPD_FLAG,
STATUS_ZABSF_PP_V_SF024-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF024.
  SELECT SINGLE * FROM ZABSF_PP032 WHERE
WERKS = ZABSF_PP_V_SF024-WERKS AND
PARID = ZABSF_PP_V_SF024-PARID .
ZABSF_PP_V_SF024-MANDT =
ZABSF_PP032-MANDT .
ZABSF_PP_V_SF024-WERKS =
ZABSF_PP032-WERKS .
ZABSF_PP_V_SF024-PARID =
ZABSF_PP032-PARID .
ZABSF_PP_V_SF024-PARVA =
ZABSF_PP032-PARVA .
    SELECT SINGLE * FROM ZABSF_PP032_T WHERE
WERKS = ZABSF_PP032-WERKS AND
PARID = ZABSF_PP032-PARID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF024-PARTXT =
ZABSF_PP032_T-PARTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF024-PARTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF024 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF024-WERKS TO
ZABSF_PP032-WERKS .
MOVE ZABSF_PP_V_SF024-PARID TO
ZABSF_PP032-PARID .
MOVE ZABSF_PP_V_SF024-MANDT TO
ZABSF_PP032-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP032'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP032 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP032'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP032-WERKS TO
ZABSF_PP032_T-WERKS .
MOVE ZABSF_PP032-PARID TO
ZABSF_PP032_T-PARID .
MOVE SY-LANGU TO
ZABSF_PP032_T-SPRAS .
MOVE ZABSF_PP_V_SF024-MANDT TO
ZABSF_PP032_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP032_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP032_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP032_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
