*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF010................................*
FORM GET_DATA_ZABSF_PP_V_SF010.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP011 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF010 .
ZABSF_PP_V_SF010-MANDT =
ZABSF_PP011-MANDT .
ZABSF_PP_V_SF010-AREAID =
ZABSF_PP011-AREAID .
ZABSF_PP_V_SF010-WERKS =
ZABSF_PP011-WERKS .
ZABSF_PP_V_SF010-ARBPL =
ZABSF_PP011-ARBPL .
ZABSF_PP_V_SF010-STPRSNID =
ZABSF_PP011-STPRSNID .
ZABSF_PP_V_SF010-ENDDA =
ZABSF_PP011-ENDDA .
ZABSF_PP_V_SF010-BEGDA =
ZABSF_PP011-BEGDA .
ZABSF_PP_V_SF010-NOTIF_TYPE =
ZABSF_PP011-NOTIF_TYPE .
ZABSF_PP_V_SF010-TIP_RESPON =
ZABSF_PP011-TIP_RESPON .
ZABSF_PP_V_SF010-TIP_STOP =
ZABSF_PP011-TIP_STOP .
ZABSF_PP_V_SF010-OEE =
ZABSF_PP011-OEE .
ZABSF_PP_V_SF010-INACT =
ZABSF_PP011-INACT .
    SELECT SINGLE * FROM ZABSF_PP011_T WHERE
AREAID = ZABSF_PP011-AREAID AND
WERKS = ZABSF_PP011-WERKS AND
ARBPL = ZABSF_PP011-ARBPL AND
STPRSNID = ZABSF_PP011-STPRSNID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF010-STPRSN_DESC =
ZABSF_PP011_T-STPRSN_DESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF010.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF010 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF010.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF010-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP011 WHERE
  AREAID = ZABSF_PP_V_SF010-AREAID AND
  WERKS = ZABSF_PP_V_SF010-WERKS AND
  ARBPL = ZABSF_PP_V_SF010-ARBPL AND
  STPRSNID = ZABSF_PP_V_SF010-STPRSNID AND
  ENDDA = ZABSF_PP_V_SF010-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP011 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP011_T WHERE
    AREAID = ZABSF_PP011-AREAID AND
    WERKS = ZABSF_PP011-WERKS AND
    ARBPL = ZABSF_PP011-ARBPL AND
    STPRSNID = ZABSF_PP011-STPRSNID AND
    SPRAS = SY-LANGU .
    IF SY-SUBRC = 0.
    SELECT COUNT(*) FROM ZABSF_PP011 WHERE
    AREAID EQ ZABSF_PP011_T-AREAID AND
    WERKS EQ ZABSF_PP011_T-WERKS AND
    ARBPL EQ ZABSF_PP011_T-ARBPL AND
    STPRSNID EQ ZABSF_PP011_T-STPRSNID .
      IF SY-DBCNT EQ 0.
    DELETE FROM ZABSF_PP011_T WHERE
    AREAID = ZABSF_PP011-AREAID AND
    WERKS = ZABSF_PP011-WERKS AND
    ARBPL = ZABSF_PP011-ARBPL AND
    STPRSNID = ZABSF_PP011-STPRSNID .
      ENDIF.
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP011 WHERE
  AREAID = ZABSF_PP_V_SF010-AREAID AND
  WERKS = ZABSF_PP_V_SF010-WERKS AND
  ARBPL = ZABSF_PP_V_SF010-ARBPL AND
  STPRSNID = ZABSF_PP_V_SF010-STPRSNID AND
  ENDDA = ZABSF_PP_V_SF010-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP011.
    ENDIF.
ZABSF_PP011-MANDT =
ZABSF_PP_V_SF010-MANDT .
ZABSF_PP011-AREAID =
ZABSF_PP_V_SF010-AREAID .
ZABSF_PP011-WERKS =
ZABSF_PP_V_SF010-WERKS .
ZABSF_PP011-ARBPL =
ZABSF_PP_V_SF010-ARBPL .
ZABSF_PP011-STPRSNID =
ZABSF_PP_V_SF010-STPRSNID .
ZABSF_PP011-ENDDA =
ZABSF_PP_V_SF010-ENDDA .
ZABSF_PP011-BEGDA =
ZABSF_PP_V_SF010-BEGDA .
ZABSF_PP011-NOTIF_TYPE =
ZABSF_PP_V_SF010-NOTIF_TYPE .
ZABSF_PP011-TIP_RESPON =
ZABSF_PP_V_SF010-TIP_RESPON .
ZABSF_PP011-TIP_STOP =
ZABSF_PP_V_SF010-TIP_STOP .
ZABSF_PP011-OEE =
ZABSF_PP_V_SF010-OEE .
ZABSF_PP011-INACT =
ZABSF_PP_V_SF010-INACT .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP011 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP011 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZABSF_PP011_T WHERE
    AREAID = ZABSF_PP011-AREAID AND
    WERKS = ZABSF_PP011-WERKS AND
    ARBPL = ZABSF_PP011-ARBPL AND
    STPRSNID = ZABSF_PP011-STPRSNID AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZABSF_PP011_T.
ZABSF_PP011_T-AREAID =
ZABSF_PP011-AREAID .
ZABSF_PP011_T-WERKS =
ZABSF_PP011-WERKS .
ZABSF_PP011_T-ARBPL =
ZABSF_PP011-ARBPL .
ZABSF_PP011_T-STPRSNID =
ZABSF_PP011-STPRSNID .
ZABSF_PP011_T-SPRAS =
SY-LANGU .
      ENDIF.
ZABSF_PP011_T-STPRSN_DESC =
ZABSF_PP_V_SF010-STPRSN_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP011_T ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP011_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF010-UPD_FLAG,
STATUS_ZABSF_PP_V_SF010-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF010.
  SELECT SINGLE * FROM ZABSF_PP011 WHERE
AREAID = ZABSF_PP_V_SF010-AREAID AND
WERKS = ZABSF_PP_V_SF010-WERKS AND
ARBPL = ZABSF_PP_V_SF010-ARBPL AND
STPRSNID = ZABSF_PP_V_SF010-STPRSNID AND
ENDDA = ZABSF_PP_V_SF010-ENDDA .
ZABSF_PP_V_SF010-MANDT =
ZABSF_PP011-MANDT .
ZABSF_PP_V_SF010-AREAID =
ZABSF_PP011-AREAID .
ZABSF_PP_V_SF010-WERKS =
ZABSF_PP011-WERKS .
ZABSF_PP_V_SF010-ARBPL =
ZABSF_PP011-ARBPL .
ZABSF_PP_V_SF010-STPRSNID =
ZABSF_PP011-STPRSNID .
ZABSF_PP_V_SF010-ENDDA =
ZABSF_PP011-ENDDA .
ZABSF_PP_V_SF010-BEGDA =
ZABSF_PP011-BEGDA .
ZABSF_PP_V_SF010-NOTIF_TYPE =
ZABSF_PP011-NOTIF_TYPE .
ZABSF_PP_V_SF010-TIP_RESPON =
ZABSF_PP011-TIP_RESPON .
ZABSF_PP_V_SF010-TIP_STOP =
ZABSF_PP011-TIP_STOP .
ZABSF_PP_V_SF010-OEE =
ZABSF_PP011-OEE .
ZABSF_PP_V_SF010-INACT =
ZABSF_PP011-INACT .
    SELECT SINGLE * FROM ZABSF_PP011_T WHERE
AREAID = ZABSF_PP011-AREAID AND
WERKS = ZABSF_PP011-WERKS AND
ARBPL = ZABSF_PP011-ARBPL AND
STPRSNID = ZABSF_PP011-STPRSNID AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZABSF_PP_V_SF010-STPRSN_DESC =
ZABSF_PP011_T-STPRSN_DESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSF_PP_V_SF010-STPRSN_DESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF010 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF010-AREAID TO
ZABSF_PP011-AREAID .
MOVE ZABSF_PP_V_SF010-WERKS TO
ZABSF_PP011-WERKS .
MOVE ZABSF_PP_V_SF010-ARBPL TO
ZABSF_PP011-ARBPL .
MOVE ZABSF_PP_V_SF010-STPRSNID TO
ZABSF_PP011-STPRSNID .
MOVE ZABSF_PP_V_SF010-ENDDA TO
ZABSF_PP011-ENDDA .
MOVE ZABSF_PP_V_SF010-MANDT TO
ZABSF_PP011-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP011'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP011 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP011'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZABSF_PP011-AREAID TO
ZABSF_PP011_T-AREAID .
MOVE ZABSF_PP011-WERKS TO
ZABSF_PP011_T-WERKS .
MOVE ZABSF_PP011-ARBPL TO
ZABSF_PP011_T-ARBPL .
MOVE ZABSF_PP011-STPRSNID TO
ZABSF_PP011_T-STPRSNID .
MOVE SY-LANGU TO
ZABSF_PP011_T-SPRAS .
MOVE ZABSF_PP_V_SF010-MANDT TO
ZABSF_PP011_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP011_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP011_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP011_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
