*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations

*Temp order detail
TYPES: BEGIN OF ty_prdord_temp,
         aufnr    TYPE aufnr,
         objnr    TYPE j_objnr,
         auart    TYPE auart,
         gstrp    TYPE pm_ordgstrp,
         gltrp    TYPE co_gltrp,
         gstrs    TYPE co_gstrs,
         gsuzs    TYPE co_gsuzs,
         gltrs    TYPE co_gltrs,
         ftrmi    TYPE co_ftrmi,
         gamng    TYPE gamng,
         gmein    TYPE meins,
         plnbez   TYPE matnr,
         plnty    TYPE plnty,
         plnnr    TYPE plnnr,
         stlbez   TYPE matnr,
         aufpl    TYPE co_aufpl,
         aplzl    TYPE co_aplzl,
         trmdt    TYPE trmdt,
         vornr    TYPE vornr,
         ltxa1    TYPE ltxa1,
         steus    TYPE steus,
         rueck    TYPE co_rueck,
         rmzhl    TYPE co_rmzhl,
         lmnga    TYPE ru_lmnga,
         stat     TYPE j_status,
         zerma    TYPE dzerma,
         autwe    TYPE autwe,
         ruek     TYPE ruek,
         marco    TYPE flag,
         cy_seqnr TYPE cy_seqnr,
       END OF ty_prdord_temp.

*Unassign order detail
TYPES: BEGIN OF ty_prdord_unassign,
         aufnr  TYPE aufnr,
         gstrs  TYPE co_gstrs,
         gsuzs  TYPE co_gsuzs,
         plnbez TYPE matnr,
         stlbez TYPE matnr,
         vornr  TYPE vornr,
         ltxa1  TYPE ltxa1,
         stat   TYPE j_status,
         steus  TYPE steus,
         gamng    TYPE gamng,
       END OF ty_prdord_unassign.
