*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZABSF_PP_V_SF045................................*
FORM GET_DATA_ZABSF_PP_V_SF045.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABSF_PP068 WHERE
(VIM_WHERETAB) .
    CLEAR ZABSF_PP_V_SF045 .
ZABSF_PP_V_SF045-MANDT =
ZABSF_PP068-MANDT .
ZABSF_PP_V_SF045-WC_STATUS =
ZABSF_PP068-WC_STATUS .
ZABSF_PP_V_SF045-STPRSNID =
ZABSF_PP068-STPRSNID .
ZABSF_PP_V_SF045-COLOR =
ZABSF_PP068-COLOR .
<VIM_TOTAL_STRUC> = ZABSF_PP_V_SF045.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSF_PP_V_SF045 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSF_PP_V_SF045.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSF_PP_V_SF045-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP068 WHERE
  WC_STATUS = ZABSF_PP_V_SF045-WC_STATUS AND
  STPRSNID = ZABSF_PP_V_SF045-STPRSNID .
    IF SY-SUBRC = 0.
    DELETE ZABSF_PP068 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABSF_PP068 WHERE
  WC_STATUS = ZABSF_PP_V_SF045-WC_STATUS AND
  STPRSNID = ZABSF_PP_V_SF045-STPRSNID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABSF_PP068.
    ENDIF.
ZABSF_PP068-MANDT =
ZABSF_PP_V_SF045-MANDT .
ZABSF_PP068-WC_STATUS =
ZABSF_PP_V_SF045-WC_STATUS .
ZABSF_PP068-STPRSNID =
ZABSF_PP_V_SF045-STPRSNID .
ZABSF_PP068-COLOR =
ZABSF_PP_V_SF045-COLOR .
    IF SY-SUBRC = 0.
    UPDATE ZABSF_PP068 ##WARN_OK.
    ELSE.
    INSERT ZABSF_PP068 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSF_PP_V_SF045-UPD_FLAG,
STATUS_ZABSF_PP_V_SF045-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSF_PP_V_SF045.
  SELECT SINGLE * FROM ZABSF_PP068 WHERE
WC_STATUS = ZABSF_PP_V_SF045-WC_STATUS AND
STPRSNID = ZABSF_PP_V_SF045-STPRSNID .
ZABSF_PP_V_SF045-MANDT =
ZABSF_PP068-MANDT .
ZABSF_PP_V_SF045-WC_STATUS =
ZABSF_PP068-WC_STATUS .
ZABSF_PP_V_SF045-STPRSNID =
ZABSF_PP068-STPRSNID .
ZABSF_PP_V_SF045-COLOR =
ZABSF_PP068-COLOR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSF_PP_V_SF045 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSF_PP_V_SF045-WC_STATUS TO
ZABSF_PP068-WC_STATUS .
MOVE ZABSF_PP_V_SF045-STPRSNID TO
ZABSF_PP068-STPRSNID .
MOVE ZABSF_PP_V_SF045-MANDT TO
ZABSF_PP068-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABSF_PP068'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABSF_PP068 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABSF_PP068'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
